### ISSUE TITLE
Investigate why actions are failing 

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/boggart#90]
Investigate why actions are failing 

- https://github.com/edoardottt/boggart/actions/runs/6508445195/job/17677819783
- https://github.com/edoardottt/boggart/actions/runs/6508445196/job/17677819779

**Comment by sagar2395** [comment]
@edoardottt I would like to work on this issue

**Comment by edoardottt** [comment]
Done @sagar2395

**Comment by sagar2395** [comment]
@edoardottt -Version 1.18 is causing issue, that's why build is failing. So, I updated to 1.21.3 version which is latest, let me know if it should be updated to any other version.

Also, ioutil library is deprecated now, so I updated the code.

**Comment by edoardottt** [comment]
Completed, thanks @sagar2395 !
