### ISSUE TITLE
Add pagination to query results

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/boggart#93]
When using a query in the `Query DB` function of the dashboard (http://localhost:8093/query) all the results are shown in a single HTML page.

Add pagination so that the HTML generated isn't huge, let's say 50 or 100 requests per page.

**Comment by edoardottt** [comment]
Done @codenoid

**Comment by codenoid** [comment]
#97

**Comment by edoardottt** [comment]
Completed, thanks @codenoid !

It looks like you're good at it :) Feel free to open new issues, it's always a pleasure to collaborate with such good devs like you
